import type { Metadata } from "next";
// import localFont from "next/font/local";
import { Raleway } from "next/font/google";
import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
// const roboto = localFont({
//   src: [
//     { path: "/fonts/Roboto-Regular.woff", weight: "400", style: "normal" },
//     { path: "/fonts/Roboto-Bold.woff", weight: "700", style: "normal" },
//     { path: "/fonts/Roboto-Medium.woff", weight: "400", style: "italic" },
//   ],
//   variable: "--font-roboto",
// });
const raleway = Raleway({
  subsets: ["latin"], // Adjust subsets as needed
  variable: "--font-raleway", // Custom CSS variable for Raleway
  weight: ["400", "700"], // Add weights you need
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
